### ISSUE TITLE
Adding more resource commands, cogs

### ISSUE THREAD

**Issue by 0xMukesh** [Bauddhik-Geeks/Bauddhik-Geeks-Discord-bot#1]
Hello 👋 ,
I want to work on this issue 

I will add more resource commands, such as this [one](https://github.com/Bauddhik-Geeks/Bauddhik-Geeks-Discord-bot/blob/main/main.py#L142-L147) for other languages as well 

I will make a [cogs](https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html) system so that it will be easier to contribute in the future and the organisation would be great as well

**Comment by Mrinank-Bhowmick** [comment]
> Hello 👋 ,
> I want to work on this issue 
> 
> I will add more resource commands, such as this [one](https://github.com/Bauddhik-Geeks/Bauddhik-Geeks-Discord-bot/blob/main/main.py#L142-L147) for other languages as well 
> 
> I will make a [cogs](https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html) system so that it will be easier to contribute in the future and the organisation would be great as well 
> 

Hey @Kira272921 👋,
Go ahead for the contributions,
😊 but keep in mind not to change the whole main.py file or all existing commands with cogs as it will be helpful for **beginners** .
You can start your contribution after the last command.
Try to provide #comments with short description in code.
_(development phase)some errors can be there while running, please try to coperate with it._

**Comment by 0xMukesh** [comment]
> > Hello 👋 ,
> > I want to work on this issue
> > I will add more resource commands, such as this [one](https://github.com/Bauddhik-Geeks/Bauddhik-Geeks-Discord-bot/blob/main/main.py#L142-L147) for other languages as well
> > I will make a [cogs](https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html) system so that it will be easier to contribute in the future and the organisation would be great as well
> 
> Hey @Kira272921 👋, Go ahead for the contributions, 😊 but keep in mind not to change the whole main.py file or all existing commands with cogs as it will be helpful for **beginners** . You can start your contribution after the last command. Try to provide #comments with short description in code. _(development phase)some errors can be there while running, please try to coperate with it._

Sure 👍

**Comment by Patrikguarda7** [comment]
cioa

**Comment by Patrikguarda7** [comment]
ciao Cseakima 
527

**Comment by Patrikguarda7** [comment]
ciao Gesima
