### ISSUE TITLE
Patrikguarda7

### ISSUE THREAD

**Issue by Patrikguarda7** [Bauddhik-Geeks/Bauddhik-Geeks-Discord-bot#3]
@Kira272921 
Ciao Accedi

Inserisci username (nel formato MSSQLxxxx) e password del database MSSQL che desideri gestire

Patrikguarda@outlook.com

**Comment by 0xMukesh** [comment]
@EFFLUX110 @Nitesh-thapliyal Hey! This seems like some kind of scam 
Could you please look into it ?
