### ISSUE TITLE
feat [new command]: GitHub search 

### ISSUE THREAD

**Issue by 0xMukesh** [Bauddhik-Geeks/Bauddhik-Geeks-Discord-bot#5]
Hey 👋,
I want to add a new command to the bot, i.e `GitHub search`

Using that command, we can search through entire GitHub by simple discord commands

We can get the lists of repos made/forked by the user 
We can get the number of stars, forks on a repo, the files inside a repo 

I want to work on this issue, I will be using `PyGithub` module as well as `GitHub API`

**Comment by Mrinank-Bhowmick** [comment]
> Hey 👋,
> I want to add a new command to the bot, i.e `GitHub search`
> 
> Using that command, we can search through entire GitHub by simple discord commands
> 
> We can get the lists of repos made/forked by the user 
> We can get the number of stars, forks on a repo, the files inside a repo 
> 
> I want to work on this issue, I will be using `PyGithub` module as well as `GitHub API`

@Kira272921 
It will be a great feature then ,
but before going ahead you have to take permission from the moderators of the organisation if you need any **api keys** for this.
@adityamangal1 please look into this if needed.

Thanks
